id: ID045D1E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:23:12+00:00'
last_modified: '2022-06-09T06:49:54.692429+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8079
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    77A7:
      image_group_id: I1PD96746
      title: Volume 1 of skung yig phyogs sgrig
      total_pages: 246
      order: 1
      base_file: 77A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
