id: opecha:P007869
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8079
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  volume:
    da2a98bf1f254ae8935276e6d27d410a:
      image_group_id: I1PD96746
      title: Volume 1 of skung yig phyogs sgrig
      volume_number: 1
      total_pages: 246
  author: ''
ebook_metadata:
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  author: ''
  sku: P007869
  cover: cover.jpg
  layers:
  - pagination
