id: P007869
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8079
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  author: ''
  volumes:
    b488bf3ab4b347a8909e9596417d2f20:
      image_group_id: I1PD96746
      title: ''
      volume_number: 1
      total_pages: 246
ebook_metadata:
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  author: ''
  sku: P007869
  cover: cover.jpg
  layers:
  - pagination
