id: P007869
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ8079
  title: སྐུང་ཡིག་ཕྱོགས་སྒྲིག་
  author: ''
  volumes:
    da2a98bf1f254ae8935276e6d27d410a:
      image_group_id: I1PD96746
      title: Volume 1 of skung yig phyogs sgrig
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
